###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Thu Aug 13 21:47:39 2026

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       mig_7series_1.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A35T-FGG484
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         310.07999999999998 MHz
##                    Time Period:       3225 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K256M16XX-107
## Data Width: 16
## Time Period: 3225
## Data Mask: 1
##################################################################################################

create_clock -period 5 [get_ports clk_ref_i]
          